### ISSUE TITLE
Nomes de arquivos devem ser em minúsculas e sem acentuação ou cedilha

### ISSUE THREAD

**Issue by fabriciofx** [LucianoBruno1/DSWI#1]
Nomes de arquivos devem ser em minúsculas e sem acentuação ou cedilha. Devemos renomeá-los para se adequar ao padrão.

**Comment by LucianoBruno1** [comment]
Todos foram corrigidos.

**Comment by fabriciofx** [comment]
@LucianoBruno1 ok!
